baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test site for mod-juxtapose'

[main]
  enableDarkMode = true

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser.attribute]
block = true

[module]
  # Build and serve using local mod-juxtapose clone declared in the named Hugo workspace:
  workspace = "mod-juxtapose.work"
  replacements = "github.com/anoduck/mod-juxtapose -> ../.."

  [[module.imports]]
    path = "github.com/anoduck/mod-juxtapose"
  [[module.imports.mounts]]
    source = "layouts"
    target = "layouts"